### ISSUE TITLE
Add support for mongodb 4.0 to align with current installer script

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/ansible-st2#193]
https://github.com/StackStorm/st2/issues/4098

**Tasks**
- [x] Wait for mongodb 4.0 to be support upstream in StackStorm
- [ ] Edit https://github.com/StackStorm/ansible-st2/blob/master/roles/mongodb/defaults/main.yml#L4 to install 4.0 by default on EL8, and U18
- [ ] Test installation on various platforms

**Comment by armab** [comment]
I'm good with any compatibility matrix if it mimics and follows the scripted installer versions.
Which is currently 4.0 for EL8/U18, but MongoDB 3.4 for everything else.
If we upgrade versions in default installer it's best to propagate the changes to other installers like ansible-st2 or anything else.

**Comment by armab** [comment]
Resolved by the https://github.com/StackStorm/ansible-st2/pull/266, thanks @amanda11 
MongoDB 4.0 is now consistently used all the way through StackStorm OS platforms.
