### ISSUE TITLE
General Plan

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#2]
Ansible deployment repo definitely needs some polishing/testing/improvements for mass-use.

The big point is to polish & publish it on [Ansible galaxy](https://galaxy.ansible.com/) (public hub) to get some visibility in the community. Another good thing are real [CI Integration tests](https://github.com/StackStorm/ansible-st2/issues/15), for better maintainability.

TODO: 
#### Part 1
- [x] Check for minimum requirements like `memory` (`disk` space for Mongo?)
- [x] Version check before install (check if `13.5.99` version is available)
- [x] `stable`, `unstable` support (besides of numeric `0.12.1` version)
- [x] Vagrantfile
- [x] Refactor all variables, add `st2_` prefix (best practice for Ansible Galaxy)
- [x] Upgrade to higher st2 version as well as downgrade should work
- [x] Fix Upstart
- [x] Upstart `N` action-runners
- [x] Initial Docs 

---
- [x] Support [New packages](https://stackstorm.com/2016/05/03/road-to-packages/)
- [x] Add WebUI installation
- [x] ~Use external/3rd party Ansible Galaxy roles for PostgreSQL/Mongo/RabbitMQ~
- [x] Tag all tasks, split into logical groups
- [x] Idempotence (playbook re-run shouldn't change anything unless new st2 version is available)
- [x] CI tests for better maintainability (Test-kitchen?, CircleCI?)
- [x] Extend list of variables/options to configure
- [x] Ability to configure with existing/remote installations of Mongo, RabbitMQ, PostgreSQL
- [x] Publish on Ansible galaxy https://github.com/StackStorm/ansible-st2/issues/12
  - [x] Polish, Refactor, Follow best practices
  - [x] Distribution
    - [x] Ship it as single `stackstorm.stackstorm` https://galaxy.ansible.com/StackStorm/stackstorm/
    - [ ] Split into: `st2`, `st2mistral`, `st2web`, `st2chatops` independent roles (`v1.0` ??)
  - [x] Ansible Galaxy Docs, Examples
- [x] More distros to support (currently Ubuntu is supported only)

**Comment by cognifloyd** [comment]
This has "Use external/3rd party Ansible Galaxy roles for PostgreSQL/Mongo/RabbitMQ" checked, but those changes have been removed.

**Comment by armab** [comment]
@cognifloyd Updated, thanks.
In fact, we used some external galaxy roles before. That was a long time ago when we supported just `Trusty` in `ansible-st2`.

With all the 4(6) distros we have now: Trusty, Xenial, CentOS/RHEL 6, CentOS/RHEL 7 in our roles it doesn't make sense anymore to use external galaxy roles, since it's hard to find role that will work for all the distros in the way we want.
