### ISSUE TITLE
Add more Variables/Settings to Configure

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#20]
Initial Minimum Viable implementation for installation of new packages was done in #42.

Real production use requires much more settings to configure.
- [x] Ability to use [`unstable` repo](https://packagecloud.io/StackStorm/unstable/) (?)
- [ ] Improve version/revision installation logic
- [x] Ability to adjust `st2.conf` parameters #121 
- [x] nginx-related stuff (st2web)
  - [x] Specify custom certificate #133 
- [ ] MongoDB
  - [x] Allow adjusting `st2` config `[database]` group settings via Ansible variables #121 
  - [ ] MongoDB role setting changes should inject into `st2` config.
  - [ ] Add ability to use external MongoDB server. #17 
- Much more to add [...]
